//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpSoft.UniSuperScrapper.ClientService
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OperationResult", Namespace = "http://schemas.datacontract.org/2004/07/UpSoft.UniSuperScrapper.ClientService")]
    public enum OperationResult : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fialed = 1,
    }
}
namespace UpSoft.UniSuperScrapper.DbAccess
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Balance", Namespace = "http://schemas.datacontract.org/2004/07/UpSoft.UniSuperScrapper.DbAccess")]
    public partial class Balance : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private decimal AmountField;

        private int IdField;

        private System.DateTime TimeStampField;

        private int UserIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://upsoft.com.au", ConfigurationName = "IUniSuperScrapperClientService")]
public interface IUniSuperScrapperClientService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/RegisterUser", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/RegisterUserResponse")]
    UpSoft.UniSuperScrapper.ClientService.OperationResult RegisterUser(string firstName, string lastName, string midName, string userName, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/RegisterUser", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/RegisterUserResponse")]
    System.Threading.Tasks.Task<UpSoft.UniSuperScrapper.ClientService.OperationResult> RegisterUserAsync(string firstName, string lastName, string midName, string userName, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/Login", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/LoginResponse")]
    UpSoft.UniSuperScrapper.ClientService.OperationResult Login(string userName, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/Login", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/LoginResponse")]
    System.Threading.Tasks.Task<UpSoft.UniSuperScrapper.ClientService.OperationResult> LoginAsync(string userName, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/GetBalance", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/GetBalanceResponse")]
    GetBalanceResponse GetBalance(GetBalanceRequest request);

    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/GetBalance", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/GetBalanceResponse")]
    System.Threading.Tasks.Task<GetBalanceResponse> GetBalanceAsync(GetBalanceRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/GetHistory", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/GetHistoryResponse")]
    GetHistoryResponse GetHistory(GetHistoryRequest request);

    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action = "http://upsoft.com.au/IUniSuperScrapperClientService/GetHistory", ReplyAction = "http://upsoft.com.au/IUniSuperScrapperClientService/GetHistoryResponse")]
    System.Threading.Tasks.Task<GetHistoryResponse> GetHistoryAsync(GetHistoryRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetBalance", WrapperNamespace = "http://upsoft.com.au", IsWrapped = true)]
public partial class GetBalanceRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 0)]
    public int userId;

    public GetBalanceRequest()
    {
    }

    public GetBalanceRequest(int userId)
    {
        this.userId = userId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetBalanceResponse", WrapperNamespace = "http://upsoft.com.au", IsWrapped = true)]
public partial class GetBalanceResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 0)]
    public UpSoft.UniSuperScrapper.ClientService.OperationResult GetBalanceResult;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 1)]
    public UpSoft.UniSuperScrapper.DbAccess.Balance balance;

    public GetBalanceResponse()
    {
    }

    public GetBalanceResponse(UpSoft.UniSuperScrapper.ClientService.OperationResult GetBalanceResult, UpSoft.UniSuperScrapper.DbAccess.Balance balance)
    {
        this.GetBalanceResult = GetBalanceResult;
        this.balance = balance;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetHistory", WrapperNamespace = "http://upsoft.com.au", IsWrapped = true)]
public partial class GetHistoryRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 0)]
    public int userId;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 1)]
    public System.TimeSpan timespan;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 2)]
    public UpSoft.UniSuperScrapper.DbAccess.Balance[] balances;

    public GetHistoryRequest()
    {
    }

    public GetHistoryRequest(int userId, System.TimeSpan timespan, UpSoft.UniSuperScrapper.DbAccess.Balance[] balances)
    {
        this.userId = userId;
        this.timespan = timespan;
        this.balances = balances;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetHistoryResponse", WrapperNamespace = "http://upsoft.com.au", IsWrapped = true)]
public partial class GetHistoryResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 0)]
    public UpSoft.UniSuperScrapper.ClientService.OperationResult GetHistoryResult;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://upsoft.com.au", Order = 1)]
    public UpSoft.UniSuperScrapper.DbAccess.Balance[] balances;

    public GetHistoryResponse()
    {
    }

    public GetHistoryResponse(UpSoft.UniSuperScrapper.ClientService.OperationResult GetHistoryResult, UpSoft.UniSuperScrapper.DbAccess.Balance[] balances)
    {
        this.GetHistoryResult = GetHistoryResult;
        this.balances = balances;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUniSuperScrapperClientServiceChannel : IUniSuperScrapperClientService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UniSuperScrapperClientServiceClient : System.ServiceModel.ClientBase<IUniSuperScrapperClientService>, IUniSuperScrapperClientService
{

    public UniSuperScrapperClientServiceClient()
    {
    }

    public UniSuperScrapperClientServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UniSuperScrapperClientServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UniSuperScrapperClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UniSuperScrapperClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public UpSoft.UniSuperScrapper.ClientService.OperationResult RegisterUser(string firstName, string lastName, string midName, string userName, string password)
    {
        return base.Channel.RegisterUser(firstName, lastName, midName, userName, password);
    }

    public System.Threading.Tasks.Task<UpSoft.UniSuperScrapper.ClientService.OperationResult> RegisterUserAsync(string firstName, string lastName, string midName, string userName, string password)
    {
        return base.Channel.RegisterUserAsync(firstName, lastName, midName, userName, password);
    }

    public UpSoft.UniSuperScrapper.ClientService.OperationResult Login(string userName, string password)
    {
        return base.Channel.Login(userName, password);
    }

    public System.Threading.Tasks.Task<UpSoft.UniSuperScrapper.ClientService.OperationResult> LoginAsync(string userName, string password)
    {
        return base.Channel.LoginAsync(userName, password);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBalanceResponse IUniSuperScrapperClientService.GetBalance(GetBalanceRequest request)
    {
        return base.Channel.GetBalance(request);
    }

    public UpSoft.UniSuperScrapper.ClientService.OperationResult GetBalance(int userId, out UpSoft.UniSuperScrapper.DbAccess.Balance balance)
    {
        GetBalanceRequest inValue = new GetBalanceRequest();
        inValue.userId = userId;
        GetBalanceResponse retVal = ((IUniSuperScrapperClientService)(this)).GetBalance(inValue);
        balance = retVal.balance;
        return retVal.GetBalanceResult;
    }

    public System.Threading.Tasks.Task<GetBalanceResponse> GetBalanceAsync(GetBalanceRequest request)
    {
        return base.Channel.GetBalanceAsync(request);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetHistoryResponse IUniSuperScrapperClientService.GetHistory(GetHistoryRequest request)
    {
        return base.Channel.GetHistory(request);
    }

    public UpSoft.UniSuperScrapper.ClientService.OperationResult GetHistory(int userId, System.TimeSpan timespan, ref UpSoft.UniSuperScrapper.DbAccess.Balance[] balances)
    {
        GetHistoryRequest inValue = new GetHistoryRequest();
        inValue.userId = userId;
        inValue.timespan = timespan;
        inValue.balances = balances;
        GetHistoryResponse retVal = ((IUniSuperScrapperClientService)(this)).GetHistory(inValue);
        balances = retVal.balances;
        return retVal.GetHistoryResult;
    }

    public System.Threading.Tasks.Task<GetHistoryResponse> GetHistoryAsync(GetHistoryRequest request)
    {
        return base.Channel.GetHistoryAsync(request);
    }
}
