//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace UpSoft.UniSuperScrapper.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Balance
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public System.DateTime TimeStamp { get; set; }
        [DataMember]
        public decimal Amount { get; set; }
        [DataMember]
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
