//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpSoft.UniSuperScrapper.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Balances = new HashSet<Balance>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UnisuperUsername { get; set; }
        public string UnisuperPassword { get; set; }
    
        public virtual ICollection<Balance> Balances { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
